In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA

In [3]:
eu_data = pd.read_csv('final_eu_data.csv')
eu_data

,country,week,ContainmentHealthIndex,population,case_weekly_count,case_rate_14_day,case_cumulative_count,death_weekly_count,death_rate_14_day,death_cumulative_count,sdi
0,Austria,9,14.100000,8858775.0,14.0,0.158035,14.0,0.0,0.000000,0.0,40.066431
1,Austria,10,15.748571,8858775.0,88.0,1.151401,102.0,0.0,0.000000,0.0,43.010222
2,Austria,11,43.221429,8858775.0,758.0,9.549853,860.0,1.0,0.112882,1.0,54.770036
3,Austria,12,63.551429,8858775.0,2771.0,39.836208,3631.0,15.0,1.806119,16.0,84.912066
4,Austria,13,66.480000,8858775.0,5182.0,89.775392,8813.0,70.0,9.595006,86.0,90.277739
...,...,...,...,...,...,...,...,...,...,...,...
941,United Kingdom,47,60.991429,66647112.0,142727.0,480.188849,1512045.0,2817.0,85.630117,54751.0,67.466447
942,United Kingdom,48,61.540000,66647112.0,105282.0,372.122651,1617327.0,3494.0,94.692775,58245.0,66.386354
943,United Kingdom,49,58.717143,66647112.0,105915.0,316.888450,1723242.0,3000.0,97.438581,61245.0,62.005753
944,United Kingdom,50,65.330000,66647112.0,126161.0,348.216139,1849403.0,2925.0,88.901076,64170.0,58.534482
945,United Kingdom,51,69.542857,66647112.0,190744.0,475.496973,2040147.0,3231.0,92.367093,67401.0,59.337215

In [ ]:
for state in merged['statename'].value_counts().index:
  state_dat = merged.loc[merged['statename']==state]
  plt.figure()
  plt.plot(pd.to_datetime(state_dat['date']), state_dat[['ContainmentHealthIndex', 'shadow_index_normalized']])
  plt.ylim(0,100)
  plt.title(state)